torch/cunn

test.lua

Unit tests for the new Euclidean module (https://github.com/torch/nn/pull/128). I only added unit test for the batch mode as it is the only parts that acts different with cuda. 
The speedup can be surprising:
```bash
------------------------------------------------------------------------------------------------	
|  Module                                                                          |  Speedup    |	
------------------------------------------------------------------------------------------------	
| Euclidean backward 16 50 <- 16 73                                                | 2.68        |	
| Euclidean forward 24 32 -> 24 41                                                 | 5.47        |	
--------------------------------------------------------------------------------------- …
```

Euclidean unit tests

---

SpatialAveragePooling.cu

Use atomic version of subgradinput in the non-batch case if kH != dH or
kW != dW.

Fix SpatialAveragePooling.

---

SpatialConvolutionCUDA.cu

It used to overwrite the gradients instead of accumulate them.

Fix SpatialConvolutionCUDA:accGradParameters.

---

TransferGPU.lua
doc/cunnmodules.md
init.lua
test.lua
utils.lua

With cutorch auto-mode, multi-gpu models can be run without explicitly
updating the device. However, copies must be explicit, so a
TransferDevice module is necessary to make the copy.
Here's an example multi-GPU module (added as a test):
```lua
cutorch.setDevice(0)
net = nn.Sequential()
for i = 1,3 do
net:add(nn.Linear(1000,1000):cuda(i))
net:add(nn.SoftMax():cuda(i))
net:add(nn.TransferDevice(i, i+1)) -- a new little shim in cunn
end
local input = torch.CudaTensorOn(1, 1000)
local output = net:forward(input)
print(output:getDevice())
local gradOutput = output/100
local gradInput = net:backward(input, gradOutput)
print(gradInput:getDevice())
```

Add TransferDevice module.

---

DataParallelTable.lua
test_DataParallelTable.lua

- cleaned up syntax (camelCase)
- got rid of global variables (use th -g to monitor globals);
there were 2 of them in DataParallelTable
- supporting batches of arbitrary sizes: do not have to be
multiples of nb of GPUs anymore; added tests for that
(so 3 GPUs can be used for batches of size 128, and 
for cases where batch size varies dynamically, everything
still works)

DataParallelTable cleanup/refactoring.

---

LookupTable.cu
init.cu
test.lua

This is a CUDA implementation of nn.LookupTable based on LookupTableGPU from fbcunn.
It doesn't support "scaleGradByFreq" option. If anyone wants that on the GPU, I can implement it but it'll be a bit of work.

Lookup table GPU implementation based on LookupTableGPU from fbcunn

---

test.lua

after https://github.com/torch/cunn/pull/98 input tensor size could go negative and test would fail

reduce SpatialConvolution padW and padH bounds in test

---

LookupTable.cu
test.lua

Fixes issue #104
The gradient computation in LookupTable was incorrect for
tables with more than 128 features when the input was larger
than 768.

Fix incorrect LookupTable backward pass

---

TemporalMaxPooling.cu

This fixes issue #108. The bug was very obvious and simple.
Tested for both forward and backward propagation on inputs of huge lengths. Did not touch test because it may blow up the time, but let me know if you want it there.

Fix index error when length is more than 1024 for TemporalMaxPooling

---

SpatialMaxPooling.cu
test.lua

This version is
* Deterministic (according to @mys007)
* Faster (close to cudnn)
* Supports floor and ceil modes
* Supports padW and padH
* Uses 2 times less memory (stores only indexes, not x and y as before) as CPU version
(kernels borrowed from caffe)
CPU version is here https://github.com/torch/nn/pull/309, both PRs are cross-reviewed by me and @fmassa

Deterministic max-pooling

---

PReLU.cu

Wonder why I used it, this API should not have been used in cunn. Fixes segfault when running cunn tests on OS X.

THCudaTensor_sum instead of reduceDim in PReLU

---

SpatialAdaptiveMaxPooling.cu
test.lua

Reduces the forward times for non-contiguous Tensors in the non-batched case by avoiding memory copies.

Add strides in SpatialAdaptiveMaxPooling to avoid memory copy in forward

---

VolumetricAveragePooling.cu
VolumetricMaxPooling.cu
init.cu
test.lua
utils.h

To solve #82, I merged ```volpool``` branch into the master. While doing this, I fixed some header issues.
th -e "require('cunn') nn.testcuda()" 
results no errors.
I noticed the argument-order confusion in Volumetric* cuda implementations, but let it go for now.

Error-free VolumetricMaxPooling & VolumetricAveragePooling merge.

---

SoftMax.cu

The module applies softmax in space and works both on a single
vector/matrix (1D/2D) or spatial vector/matrix (3D/4D).

Update SoftMax to work in spatial mode

---

DataParallelTable.lua

Hi Guys, I am proposing this PR as I find the changes convenient for my project however I am unsure if that fits into the grand plan of things so I let the experts decide. Thanks!
Commit message:
When defining a network in Torch it is customary to move it
to the currently selected GPU through a single call to the
top-level module's cuda() method.
This patch allows this by merely asserting in the type()
method that the target type is 'torch.CudaTensor', rather
that dropping an error unconditionally.
In this patch we are also conveniently moving any added
module to CUDA, since it only makes sense to add CUDA
modules to a DataParallelTable container.

Allow move to CUDA from top-level module

---

test.lua

These were failing regularly when running the tests repeatedly on my machine.

Decrease required precision for SmoothL1, mse and Tanh tests.

---

SpatialAveragePooling.cu
test.lua

cuda part for https://github.com/torch/nn/pull/365

SpatialAveragePadding padding and ceil kernels

---

SpatialMaxPooling.cu

Add a check (that is present in the C version of SpatialMaxPooling but was not in CUDA version) so that the last pooling blocks do not start out of the image.
It was the cause of some errors in nn.testcuda (defined in cunn/test.lua)

Fix SpatialMaxPooling (check if last pool block starts in image)

---

SpatialBatchNormalization.cu
init.cu
test.lua
utils.h

Adapted from @nicolasvasilache's implementation and @szagoruyko's port.
This uses less memory than the existing fbcunn implementation and on my ResNet benchmarks is slightly faster than both the current fbcunn and the cudnn implementation.
Here's a little benchmark:
https://gist.github.com/colesbury/51991501334c9e4b1728

Add SpatialBatchNormalization CUDA implementation

---

SpatialBatchNormalization.cu
test.lua

When the CUDA backwards implementation is called by accGradParameters
gradInput is nil/empty. Use the size from gradOutput instead.
I also added tests for both backward() and updateGradInput() followed by
accGradParameters() to test.lua.

Fix SpatialBatchNormalization:accGradParameters()

---

VolumetricAveragePooling.cu
VolumetricMaxPooling.cu
test.lua

The kernels for these modules were completely broken in terms of accessing the input; confusing the stride with the kernel width and improper bounds checking.
Converted average pooling to look like the loops in max pooling.
Also reduced sizes to prevent out-of-memory errors.
Other failing cunn tests seem to have been failing due to these tests (out of memory errors or memory corruption).
Original author: @wickedfoo
Date:  Sep 14 2015, 4:45 PM

fixing bugs in Volumetric Average and Max pooling

---

SpatialConvolutionLocal.cu
init.cu
test.lua
utils.h

tested on K20 with 
`th -lcunn -e "nn.testcuda{'SpatialConvolutionLocal_forward_single',   'SpatialConvolutionLocal_forward_batch', 'SpatialConvolutionLocal_backward_single',   'SpatialConvolutionLocal_backward_batch'}" `

Correct GPU implementation for locally connected layers

---

DataParallelTable.lua
doc/cunnmodules.md
test_DataParallelTable.lua

This lets us use the fastest CUDNN R4 kernels with DPT, which have much
higher launch overhead. With single-threaded dispatch, the launch
overhead from these kernels delays the second, third, and fourth GPUs so
much that it actually increases the total time.
I've also included some other optimizations:
- `gradInput` can be set to `nil` when the DataParallelTable is the
top-level module; this saves time and memory
- input can optionally be on the CPU; this saves memory on the first
GPU, and is faster when the input is in pinned memory since the copies
to each GPU happen concurrently.
This change is mostly backwards compatible, with the below caveats:
- The preferred way to add modules is by a single call to add with the
list of GPUs i.e. `:add(module, {1, 2, 3, 4})`
- …

Add multi-threading support in DataParallelTable

---

DataParallelTable.lua

Currently, when an old model checkpoint is loaded, it's `impl` field isn't initialized, so it crashes as soon as you try to do anything with the network.

Instantiate impl field in older models

---

THCUNN.lua
lib/THCUNN/THCUNN.h
lib/THCUNN/VolumetricFullConvolution.cu
lib/THCUNN/vol2col.h
test.lua

The module didn't pass gradients check and had limitations (batch mode only, constraints on kernel size and padding). This new implementation removes these limitations, and is now implemented like SpatialFullConvolution.

Fixed VolumetricFullConvolution.

---

test.lua

remove warnings about testsuite
Before:
```
Completed 567 asserts in 134 tests with 0 failures and 1 error and 1 warning
--------------------------------------------------------------------------------
distkldiv
Function call failed
...tu/torch/install/share/lua/5.1/nn/DistKLDivCriterion.lua:9: input and target 
should have the same size
stack traceback:
[C]: in function 'assert'
...tu/torch/install/share/lua/5.1/nn/DistKLDivCriterion.lua:9: in functi
on 'forward'
/home/ubuntu/torch/install/share/lua/5.1/cunn/test.lua:2954: in function
'v'
/home/ubuntu/torch/install/share/lua/5.1/cunn/test.lua:4712: in function
</home/ubuntu/torch/install/share/lua/5.1/cunn/test.lua:4710>
[C]: in function 'xpcall'
/home/ubuntu/torch/install/share/lua/5.1/torch/Tester.lua:475: in functi
on '_pcall' …
```

remove warnings about testsuite

---

test.lua

Add alias cunn.test(), following eg format of cutorch.test()
(Cos, so many times I type like:
```
luajit -l cunn -e 'cunn.test()'
-- hmmm, nope...
luajit -l cunn -e 'nn.cudatest()'
-- hmmm....
vim ~/torch/install/share/lua/5.1/cunn/test.lua
-- fine ...
luajit -l cunn -e 'nn.testcuda()'
```
)

Add alias cunn.test(), following eg format of cutorch.test()

---

lib/THCUNN/BatchNormalization.cu
lib/THCUNN/THCUNN.h
test.lua

The cunn counterpart for https://github.com/torch/nn/pull/768.
Tested on K40 with `th -lcunn -e "nn.testcuda('BatchNormalization')"`

add backpropagation in evaluation mode for batchnormalization

---

DataParallelTable.lua

Make it return the module, just like all other modules do.

Fix clearState in DataParallelTable

---

lib/THCUNN/SpatialClassNLLCriterion.cu
lib/THCUNN/THCUNN.h
lib/THCUNN/common.h
test.lua

Original `ClassNLLCriterion` is awfully slow when it comes to spatial data. It forces you to transpose it to a 2D Tensor (NCHW -> NHWC), which is pretty expensive by itself for big tensors, and then it uses a **hardcoded number of 32 threads** for processing (e.g. 1M elements)... This means that around 80% of my training loop is spent doing criterion stuff.
Here is a nice comparison from visual profiler:
On the left 100x fw+bw pass of SpatialClassNLLCriterion, on the right 1 fw+bw of ClassNLLCriterion (not including transpose).
These are the times for `4x20x512x1024` input and `4x512x1024` targets (100 runs):
| Criterion                                      | Time for 100 runs (s) |
|------------------------------------------------|-----------------------|
| SpatialClassNLLCriterion …

Add SpatialClassNLLCriterion

---

lib/THCUNN/SpatialCrossMapLRN.cu

Fix for torch@cunn#271, to make openface works on Jetson TK1.

Limit registers when LRNFillScale runs on TK1.

---

lib/THCUNN/SpatialSubSampling.cu
test.lua

Also some changes to test to make it less flaky:
- Decrease some output counts to reduce out-of-memory issues.
- Decrease some tolerances.
- Increase precision of random seed so that multiple test launches at
the same time start with different seeds.

Fix SpatialSubSampling (was doing non-atomic writes in backprop).

---

lib/THCUNN/SoftMax.cu

Fix for https://github.com/torch/cunn/issues/150.
In oder to stay compatible with compute capability 2.X devices a 3D grid is only used for inputs with width*height > 65335.
Todo:
- Analyse performance impact for 3d thread block grid
Would be great if somebody could review/test.
Beside running cunn.test() I compared with the CPU results:
```
require 'cunn'
-- cpu:
s1 = nn.SpatialSoftMax()
x1 = torch.rand(2,16,300,300)
-- gpu:
s2 = nn.SpatialSoftMax()
s2:cuda()
x2 = x1:cuda()
y1 = s1:forward(x1)
y2 = s2:forward(x2)
d = (y1-y2:double()):abs()
err_max = d:max()
err_avg = d:sum()/d:nElement()
print(string.format('err_max: %e, err_avg: %e', err_max, err_avg)) 
```

Use 3d thread blocks in SoftMax for inputs with w*h > 2^16-1

---

test_DataParallelTable.lua

test_DataParallelTable.lua broke because of an incorrect call to assert and changes to the tester and LookupTable.
This fixes the test.

Fix test_DataParallelTable.lua

---

lib/THCUNN/Abs.cu
lib/THCUNN/ELU.cu
lib/THCUNN/HardTanh.cu
lib/THCUNN/LeakyReLU.cu
lib/THCUNN/LogSigmoid.cu
lib/THCUNN/PReLU.cu
lib/THCUNN/RReLU.cu
lib/THCUNN/Sigmoid.cu
lib/THCUNN/SoftPlus.cu
lib/THCUNN/SoftShrink.cu
lib/THCUNN/SpatialReflectionPadding.cu
lib/THCUNN/SpatialReplicationPadding.cu
lib/THCUNN/Sqrt.cu
lib/THCUNN/Square.cu
lib/THCUNN/Tanh.cu
lib/THCUNN/Threshold.cu

fixes https://github.com/torch/cunn/issues/295

fixes for cutorch API changes

---

lib/THCUNN/ClassNLLCriterion.cu
lib/THCUNN/SpatialClassNLLCriterion.cu

Checks that there are as many weights as classes (before, undefined values could be used).

NLL Criteria: weight bound checking

---

lib/THCUNN/SpatialConvolutionMM.cu
lib/THCUNN/SpatialDilatedConvolution.cu
lib/THCUNN/SpatialFullConvolution.cu
lib/THCUNN/VolumetricConvolution.cu
lib/THCUNN/VolumetricFullConvolution.cu

cutorch introduced the change gemm -> Sgemm and gemv -> Sgemv in master.
Fixing it in cunn.
If one wants to use the old cutorch / cunn, 1.0-0 is a stable previous version without breaking API changes.
```bash
luarocks remove --force cutorch
luarocks remove --force cunn
luarocks install cunn 1.0-0
```

gemm -> Sgemm

---

THCUNN.lua
lib/THCUNN/LookupTable.cu
lib/THCUNN/SparseLinear.cu
lib/THCUNN/THCUNN.h

cunn counterpart for https://github.com/torch/cutorch/pull/461

fixes for multiple cuda types

---

lib/THCUNN/HardTanh.cu
test.lua

Fixes torch7 issue #734, "Inconsistent behavior of nn.Clamp in CPU and GPU modes".
Adds a simple test that gradOutput equals gradInput after backward when inplace is set.
It is possible to construct a test with inplace HardTanh where forward+backward yields
different results for nn vs cunn, but this appears to be due to the inclusive vs
exclusive bounds used for inplace vs non-inplace, respectively, so a more direct test
is preferred.

inplace is reversed in HardTanh:backward.

---

DataParallelTable.lua
test_DataParallelTable.lua

Currently, if only a part of a network is wrapped with DataParallelTable and flattenParameters is enabled, then the flat tensor created is larger than it needs to be due to an issue with offsets. This ends up copying a lot more data during every call to syncParameters.

Fix issue with flatten parameters in DataParallelTable

---

lib/THCUNN/BCECriterion.cu
lib/THCUNN/THCUNN.h
test.lua

Adds weights support to BCECriterion THCUNN implementation.
Rather than writing a special kernel, I followed [this thrust example](https://github.com/thrust/thrust/blob/master/examples/arbitrary_transformation.cu) to perform a transformation of more than two inputs, replacing `thrust::inner_product` with `thrust::transform_reduce`.
I added two new tests so BCECriterion is tested both with and without weights like in torch/nn.

BCECriterion THCUNN + Weights

---

lib/THCUNN/LogSoftMax.cu
test.lua

I updated LogSoftMax to support spatial data with a kernel that accesses the input data in "cuda" format, B x H x W x P, where B is batch size and P is number of classes, for better cache performance. The original commit from @fmassa is included in this PR.

SpatialLogSoftMax

---

DataParallelTable.lua

I had a problem in `updateGradInput` method for small batches for which one of the gpu assignment was empty. 
In `updateOutput` method, emptiness test is done using `_hasData` which includes empty tensor testing but also **empty table testing** (my net is taking table input).
The patch just does the same for `__backward` - let me know if you have any question.

test on inputGpu emptiness symmetric in backward and forward

---

lib/THCUNN/RReLU.cu
lib/THCUNN/SharedMem.cuh
lib/THCUNN/SparseLinear.cu
lib/THCUNN/THCHalfAutoNumerics.cuh

This should address https://github.com/torch/torch7/issues/832.
I tested compilation with CUDA 7.0; it fails without and passes with this PR.

Protect half operations with CUDA_HALF_TENSOR with generic modules.

---

lib/THCUNN/generic/SparseLinear.cu
lib/THCUNN/generic/SpatialAdaptiveMaxPooling.cu
lib/THCUNN/generic/SpatialSubSampling.cu
lib/THCUNN/generic/SpatialUpSamplingNearest.cu
lib/THCUNN/generic/TemporalConvolution.cu
lib/THCUNN/generic/VolumetricConvolution.cu
test.lua

These changes were required to get cunn tests working when using all contiguous tensors (except in cases where an arg check complains that a tensor is not contiguous).
The test I used is here (and is not included in this pull request):
https://github.com/gchanan/cunn/commit/ae7a8363c683689087d8457e67fb50aebb923469
I'm happy to incorporate the test into a commit, but it's not obvious to me how to do that in a clean way (i.e. that doesn't complicate all the existing tests).

Add contiguous checks / auto contiguous

---

lib/THCUNN/generic/SpatialAveragePooling.cu
lib/THCUNN/generic/SpatialDilatedMaxPooling.cu
lib/THCUNN/generic/TemporalMaxPooling.cu

1. Adds gradOutput shape checks for temporal modules
2. Removes unnecessary (too restrictive and/or redundant) shape checks in Spatial Pooling modules.

Improve fix/shape checks for Temporal and Spatial modules

---

DataParallelTable.lua

Thanks to @ngimel for the fix. We discovered this bug while testing DIGITS with 4+ GPUs.
Test with:
```lua
for gpus=1,8 do
for batch=1,gpus*2 do
sum = 0
for idx=1,gpus do
start, elts = sliceRange(batch, idx, gpus)
sum = sum + elts
if elts == 0 then
break
end
end
if sum ~= batch then
print('ERROR when gpus=' .. gpus .. ' and batch=' .. batch)
end
end
end
```
The old function failed for several gpu/batch combinations:
```
ERROR when gpus=4 and batch=2	
ERROR when gpus=5 and batch=2	
ERROR when gpus=5 and batch=3	
ERROR when gpus=6 and batch=2	
ERROR when gpus=6 and batch=3	
ERROR when gpus=6 and batch=4	
ERROR when gpus=7 and batch=2	
ERROR when gpus=7 and batch=3	
ERROR when gpus=7 and batch=4	
ERROR when gpus=7 and batch=5	
ERROR when gpus=8 and batch=2	
ERROR when gpus=8 and batch=3 …
```

Fix sliceRange for when nElem < splits

---

THCUNN.lua
test.lua

This is inconsistent with cuda(), which is included from nn not cunn, but this seems more appropriate since we can check cutorch.hasHalf before adding cudaHalf() (which is consistent with how tensors conversion functions are handled).

Add cudaHalf, cudaDouble functions to nn.Module.

---

lib/THCUNN/generic/LookupTable.cu

There are two exit points in `accGradParameters` and one of them is missing a `free` on gradOutput (`newContiguous` is called on it [at the beginning](https://github.com/torch/cunn/compare/master...apaszke:lookup_leak?expand=1#diff-5d6c9b1c7b1eb8b369bb74867cb73867R18)).

Add missing free in LookupTable

---

.gitignore

Since THCUNN was made generic, this file is now generated by the build, so it makes sense to .gitignore it.

Add THCUNN_generic_h.lua to .gitignore

---

lib/THCUNN/SpatialClassNLLCriterion.cu
lib/THCUNN/generic/SpatialClassNLLCriterion.cu

Apparently in SpatialClassNLLCriterion there are so many atomicAdds, that most of the later ones suffer from serious underflows, and that results in differences between CPU and CUDA implementations as large as 5e-3. Moving the averaging to a separate kernel pushes them down to around 1e-8. I think we can afford an additional kernel launch for the sake of correctness.

Do SpatialClassNLLCriterion sizeAverage in a separate kernel

---

THCUNN.lua

with nn.
Both THNN and THCUNN define the accfloat/accdouble typedef via ffi.  The behavior of this seems to be lua version/luajit version dependent (saw test failures with luajit) and it's probably a good idea to get rid of it (as C doesn't let you redefine a typedef in any case).
Since we no longer support 'real' in the header declaration, it makes sense to just define the gsub on accreal; if we want to add back real support we'll have to do something more complicated.

Remove accreal typedef because it is defined multiple times

---

lib/THCUNN/LookupTable.cu
lib/THCUNN/generic/LookupTable.cu

cc @adamlerer 
I didn't end up keeping my custom kernels since they were hard to make faster for most cases.
Instead, I noticed that we were calling cutorch's tensor sort which is not needed: we need only sort 1 dimension, and the sort need not be a stable sort. It is slightly slower (or lost in the noise) for <= 1024 sort sizes, but notice the improvement is substantial above this size (where cutorch would use the Thrust fallback sort). This provides the following speedup:
table size | dims | batch size | relative speedup
```
100000 20 32 1x
100000 20 128 1.00379x
100000 20 512 0.92x
100000 20 2048 2.05898x
100000 20 8192 1.65208x
100000 20 16384 1.58788x
100000 100 32 0.379691x
100000 100 128 0.97193x
100000 100 512 1x
100000 100 2048 2.07871x
100000 100 8192 1.81497x
100000 100 16384 …
```

Improve cunn LookupTable performance for large batch sizes

---

test.lua

1) In cases where tests were failing with some regularity
(SmoothL1, l1cost, mse, SoftShrink-backward) scale error bounds
by (absolute) value being tested.
2) Fix some spacing issues in error messages.

Improve precision testing

---

lib/THCUNN/generic/LookupTable.cu

Fixes pytorch/pytorch#1057. Accumulator was an int, so the returned norm had no fractional part 🙂

Cast accumulator in LookupTable renorm to accreal

---

lib/THCUNN/HardTanh.cu

in-place and out-of-place updateGradOutput results are different where input=min_val or input=max_val

Fix inconsistent in-place and out-of-place for HardTanh

---

lib/THCUNN/Sigmoid.cu
lib/THCUNN/Tanh.cu
lib/THCUNN/generic/Sigmoid.cu
lib/THCUNN/generic/Tanh.cu

Sigmoid no longer uses double precision math. THC is used to compute forward.
TODO: update LogSigmoid too

Update ops for Sigmoid and Tanh

---

lib/THCUNN/FeatureLPPooling.cu
lib/THCUNN/generic/FeatureLPPooling.cu
lib/THCUNN/generic/THCUNN.h
test.lua

This diff contains the GPU kernels and calling code from the fbcunn library for FeatureLPPooling that we are contributing to cunn itself, converted to compile with modern cutorch / cunn with half, float and double support.
https://github.com/facebook/fbcunn/blob/master/src/FeatureLPPooling.cu
https://github.com/facebook/fbcunn/blob/master/src/FeatureLPPoolingHost.cpp
@soumith said he'd add the rest from here.

GPU implementation of L_p feature pooling
