- test.lua
Some CMul unit tests for https://github.com/torch/nn/pull/138
> CMul unit tests

- SpatialAveragePooling.cu
- SpatialMaxPooling.cu
- SpatialSubSampling.cu
small fix as discussed here https://github.com/torch/cunn/pull/60
> undef CUDA_MAX_THREADS in MaxPooling, SubSampling and AveragePooling

- SpatialAdaptiveMaxPooling.cu
- init.cu
- test.lua
https://github.com/torch/nn/issues/141
> Added SpatialAdaptiveMaxPooling

- MultiMarginCriterion.cu
CUDA version of this https://github.com/torch/nn/pull/157
> MultiMargin criterion supports p=2

- LogSigmoid.cu
- init.cu
- test.lua
Add matching module for nn.LogSigmoid and a test to verify it behaves
the same.
> Add LogSigmoid module.

- LogSigmoid.cu
> Use THCState in LogSigmoid.

- SpatialAveragePooling.cu
See https://github.com/torch/nn/pull/178 and https://github.com/torch/nn/pull/180
> SpatialAveragePooling divides by kW*kH

- CMakeLists.txt
- DataParallelTable.lua
- README.md
- docs/cunnmodules.md
- init.lua
- test_DataParallelTable.lua
See the docs for an explanation and usage.
After chatting with @soumith, it seems like he would prefer that the lua source goes in cunn, rather than nn (which makes sense to me since this is a GPU only related module).  It means that a) CMakeLists needs to change so that all lua source is copied and b) I needed to add docs.
> Added DataParallelTable.  Added docs.

- PReLU.cu
- SpatialConvolutionMM.cu
- VolumetricConvolution.cu
- init.cu
- test.lua
Added cuda support for PReLU jointly with @szagoruyko.
Requires nn pull request torch/nn#258 to work.
> PReLU cuda implementation

- test.lua
> global setUp variable in test.lua fix

- MultiMarginCriterion.cu
fixes a bug introduced [here](https://github.com/torch/cunn/commit/a579aec6eebb71c0bd63c2e7fa30606752913e9e#diff-0bd6b3577d671633a664145fc6172330L169)
> fix MultiMarginCriterion

- test.lua
SpatialConvolutionMM on CPU supports strides since https://github.com/torch/nn/commit/0298277b5e2478668bf82c0cef7b401139f9dc89
> test convolutions with strides != 1

- SpatialConvolutionMM.cu
- test.lua
Cuda version of https://github.com/torch/nn/pull/293
> SpatialConvolutionMM accepts padW/padH != 1

- SpatialConvolutionMM.cu
Cuda equivalent of https://github.com/torch/nn/pull/297
> Assert output size in SpatialConvolutionMM

- test.lua
There was a bug for handling 2D (batch) input in CUDA LookupTable.
This adds a test for that case.
> Add test case for 2D input to LookupTable

- SpatialConvolutionMM.cu
> Removed unused variable from SpatialConvolutionMM

- SpatialMaxPooling.cu
(forgot to update https://github.com/torch/cunn/pull/106 after https://github.com/torch/cunn/pull/110 was merged, sorry)
> SpatialMaxPooling build fix

- CMakeLists.txt
- rocks/cunn-scm-1.rockspec
Minor change: explicitly linking with LUALIB for Windows.
> Making things work under windows

- VolumetricConvolution.cu
- test.lua
Fixes #92 thanks to @kmul00 for the patch in a comment.
unit tests now properly assert to check this.
> fixing VolumetricConvolution's dimensions discrepancy from CPU

- PReLU.cu
Fixing issue #123 
The code now works identically to CPU version of nn.PReLU on 1D and 2D tensors.
I think it would be a good idea to provide a clear specification what this unit shall do with 3D and 4D tensors (for the CPU version as well) or just restrict its usage to 1D and 2D, but this seems to be outside of the scope of this fix.
> Fix issue 123: PReLU with non-shared parameters

- VolumetricAveragePooling.cu
- VolumetricMaxPooling.cu
- init.cu
- test.lua
This needs some features from https://github.com/torch/cutorch/pull/167 , so has to wait for that to merge before this can merge.
> adding VolumetricAveragePooling and VolumetricMaxPooling CUDA versions

- init.lua
- test.lua
Fixes https://github.com/torch/nn/issues/388
Adding a unit test to check for errors.
> added getParameters to be on CPU

- SmoothL1Criterion.cu
- init.cu
- test.lua
- utils.h
CUDA side for https://github.com/torch/nn/pull/376
> SmoothL1 criterion

- SpatialMaxPooling.cu
Fixes https://github.com/torch/cunn/issues/145
> Remove double free in SpatialMaxPooling

- HardTanh.cu
allows HardTanh to use a custom interval for linear region when min/max values
are specified in declaration.
> Use custom range in HardTanh

- VolumetricDeconvolution.cu
- init.cu
- test.lua
- utils.h
CUDA version for https://github.com/torch/nn/pull/441
Implemented by @dutran
> adding VolumetricDeconvolution + tests

- SpatialFractionalMaxPooling.cu
- init.cu
- test.lua
- utils.h
CUDA version of https://github.com/torch/nn/pull/442
Implemented by @wickedfoo
From paper "Fractional Max Pooling" by Ben Graham : arxiv.org/abs/1412.6071
cc: @btgraham
> adding fractional maxpooling

- DataParallelTable.lua
A patch from Natalia Gimelshein of NVIDIA, which makes DPT way more efficient.
> removing syncs from DPT, adding flattenParams

- MarginCriterion.cu
- init.cu
- test.lua
- utils.h
Hi,
Adding MarginCriterion cuda code with unit test.
I'm not very familiar with cuda, but the code was based off "MultiMarginCriterion.cu". It passes the 
unit test comparing against the non-cuda version.
-Hani
> Added MarginCriterion with unit test

- RReLU.cu
- init.cu
- test.lua
- utils.h
cunn counterpart of https://github.com/torch/nn/pull/437
> Add RReLU cunn impl

- test.lua
Remove atomic max-pooling test as there is no atomic max pooling anymore.
Also remove global variables at Volumetric modules and FractionalMaxPooling tests
> Remove atomic max-pooling test

- VolumetricConvolution.cu
Padding option wasn't previously applicable to the Volumetric Convolution, though the Cuda kernel has it. This is the Cuda version of it.
Padding can be provided in the same was as for `SpatialConvolution` :
module = nn.VolumetricConvolution(nInputPlane, nOutputPlane, kT, kW, kH, [dT], [dW], [dH], [padT], [padW], [padH])
Default is `0`
It would be wonderful if someone can do the same for the CPU version `VolumetricConvolution.c` in the `nn` package. This PR depends on [this PR](https://github.com/torch/nn/pull/392) as well for the updated `VolumetrciConvolution.lua` file in the `nn` package.
> Added Padding Option to VolumetricConvolution

- ELU.cu
- init.cu
- test.lua
- utils.h
This is the cuda implementation for the pull request torch/nn#508.
> added cuda implementation of Exponential Linear Unit (ELU)

- MarginCriterion.cu
Sorry only noticed after the PR was merged. No need for custom kernels here.
> Use thrust in MarginCriterion

- LeakyReLU.cu
- init.cu
- test.lua
- utils.h
Rebased version of https://github.com/torch/cunn/pull/156
> Added LeakyReLU to cunn

- test.lua
> fixing FullConvolution tests

- SpatialAveragePooling.cu
- SpatialCrossMapLRN.cu
- init.cu
- test.lua
- utils.h
CUDA part for https://github.com/torch/nn/pull/413
tests are coming
> SpatialCrossMapLRN

- SpatialCrossMapLRN.cu
Noticed that caffe guys did a few fixes to their kernels. This also fixes tests against cudnn.
> Update SpatialCrossMapLRN kernels

- SpatialMaxUnpooling.cu
- init.cu
- test.lua
- utils.h
Hi all.
This is the cuda version of SpatialMaxUnpooling previously proposed in torch/nn.
(https://github.com/torch/nn/pull/537)
Best,
Clément
> Add SpatialMaxUnpooling

- SpatialFullConvolution.cu
- test.lua
That mirrors the changes in https://github.com/torch/nn/pull/552
> Add adjustment term to SpatialFullConvolution to control output size

- SoftShrink.cu
- init.cu
- test.lua
- utils.h
Add missing GPU implementation of SoftShrink, as pointed out in https://github.com/torch/cunn/issues/191
> Add GPU version of SoftShrink

- SpatialBatchNormalization.cu
> Fix incorrect floor calculation

- VolumetricMaxPooling.cu
- test.lua
`CUNN` version of [this](https://github.com/torch/nn/pull/589).
modified:   VolumetricMaxPooling.cu
modified:   test.lua
> Added padding option to Volumetric Max Pooling (CUDA)

- SpatialBatchNormalization.cu
```
dim3 blocks(input.getSize(1), input.getSize(0));
dim3 threads(input.getSize(3),
min(input.getSize(2), maxThreadsPerBlock / input.getSize(3)));
SpatialBatchNormalizationUpdateOutputInference_kernel
<<<blocks, threads, 0, s>>>
(input, output, runningMean, runningVar, weight, bias, eps);
```
Current way of determining thread configuration in inference mode crashes CUDA if input.getSIze(3) i.e. the width of the image is > 1024.
maxThreadsPerBlock is 1024 for modern GPUs and in that case we get:
```
min(input.getSize(2), maxThreadsPerBlock / input.getSize(3)) =  0
```
I modifed the implementation and now it supports all input dimensions in a same way
train version does.
> Fix thread configuration in inference mode

- SpatialBatchNormalization.cu
- THCUNN.lua
- init.cu
- lib/THCUNN/THCUNN.h
- lib/THCUNN/TemporalConvolution.cu
- lib/THCUNN/TemporalMaxPooling.cu
- utils.h
cunn version of https://github.com/torch/nn/pull/623
> moving Temporal* to THCUNN

- DataParallelTable.lua
- test_DataParallelTable.lua
Before this change, calling forward & backward multiple times without calling
zeroGradParameters would compute an incorrect gradient.
Fixes #209
> Zero gradients on secondary GPUs after accGradParameters

- lib/THCUNN/MultiMarginCriterion.cu
> Fix sizeAverage bug in MultiMarginCriterion (divide by nbatch, not ndim)

- THCUNN.lua
- lib/THCUNN/LookupTable.cu
- lib/THCUNN/THCUNN.h
- test.lua
CUDA counterpart of https://github.com/torch/nn/pull/650
> adding padValue to LookupTable

- THCUNN.lua
- lib/THCUNN/MultiMarginCriterion.cu
- lib/THCUNN/THCUNN.h
CUDA counterpart of https://github.com/torch/nn/pull/652
> added weights to MultiMarginCriterion

- THCUNN.lua
- lib/THCUNN/SpatialReflectionPadding.cu
- lib/THCUNN/SpatialReplicationPadding.cu
- lib/THCUNN/THCUNN.h
- test.lua
CUDA version of https://github.com/torch/nn/pull/667
> adding SpatialReflectionPadding and SpatialReplicationPadding

- lib/THCUNN/SpatialConvolutionMM.cu
Cuda counterpart of https://github.com/torch/nn/pull/672
> Add extra checks for convolution parameters

- DataParallelTable.lua
Prevent parameters to be flattened more than once, as described in #213
> Do flattenParameters() only once

- THCUNN.lua
- lib/THCUNN/SoftMarginCriterion.cu
- lib/THCUNN/THCUNN.h
- test.lua
cunn equivalent of https://github.com/torch/nn/pull/677
> SoftMarginCriterion

- CMakeLists.txt
not relevant as we are on 6.5 at least
> Remove CMakeLists CUDA 5 os x workaround

- lib/THCUNN/ELU.cu
- lib/THCUNN/THCUNN.h
Add an option to do ELU in-place, as can already be done with ReLU.
See also: https://github.com/torch/nn/pull/704
> In-place ELU

- lib/THCUNN/MultiMarginCriterion.cu
- lib/THCUNN/THCUNN.h
make margin parameterizable in cunn.MultiMarginCriterion
prevents incorrect arg count error when using MultiMarginCriterion on CUDA device
> make margin parameterizable

- lib/THCUNN/LookupTable.cu
- lib/THCUNN/THCUNN.h
The cuda version for the pull request in nn:
https://github.com/torch/nn/pull/739
> [LookupTable] Add Max-norm constraints to LookupTable

- lib/THCUNN/SpatialFractionalMaxPooling.cu
- lib/THCUNN/VolumetricMaxPooling.cu
See also https://github.com/torch/torch7/pull/634.
> Remove use of broken THInf macro, which caused UB

- lib/THCUNN/SpatialConvolutionMM.cu
- lib/THCUNN/THCUNN.h
- test.lua
https://github.com/torch/nn/pull/776
> add noBias for nn.Linear and nn.SpatialConvolution

- test.lua
Argument order of Volumetric modules is insane...
> Fix VolumetrixMaxPooling tests

- DataParallelTable.lua
Fix for https://github.com/soumith/cudnn.torch/issues/172
> fix clearState for DataParallelTable

- DataParallelTable.lua
- test_DataParallelTable.lua
Some recent fixes and tests from @colesbury
> fixes to DataParallelTable for no parameter networks

- lib/THCUNN/SpatialConvolutionLocal.cu
- lib/THCUNN/SpatialConvolutionMM.cu
- lib/THCUNN/SpatialDilatedConvolution.cu
- lib/THCUNN/THCUNN.h
- lib/THCUNN/im2col.h
- test.lua
cunn version of https://github.com/torch/nn/pull/797
> Adding SpatialDilatedConvolution

- rocks/cunn-scm-1.rockspec
Helps with building on Ubuntu 16.04.
Copies @hughperkins's fix from https://github.com/torch/cutorch/pull/402.
> Add CMAKE_CXX_FLAGS to rockspec

- lib/THCUNN/BatchNormalization.cu
- lib/THCUNN/ClassNLLCriterion.cu
- lib/THCUNN/LogSoftMax.cu
- lib/THCUNN/LookupTable.cu
- lib/THCUNN/MultiLabelMarginCriterion.cu
- lib/THCUNN/MultiMarginCriterion.cu
- lib/THCUNN/PReLU.cu
- lib/THCUNN/RReLU.cu
- lib/THCUNN/SoftMax.cu
- lib/THCUNN/SpatialAdaptiveMaxPooling.cu
- lib/THCUNN/SpatialAveragePooling.cu
- lib/THCUNN/SpatialClassNLLCriterion.cu
- lib/THCUNN/SpatialCrossMapLRN.cu
- lib/THCUNN/SpatialFractionalMaxPooling.cu
- lib/THCUNN/SpatialMaxPooling.cu
- lib/THCUNN/SpatialMaxUnpooling.cu
- lib/THCUNN/SpatialReflectionPadding.cu
- lib/THCUNN/SpatialSubSampling.cu
- lib/THCUNN/SpatialUpSamplingNearest.cu
- lib/THCUNN/TemporalMaxPooling.cu
- lib/THCUNN/VolumetricAveragePooling.cu
- lib/THCUNN/VolumetricConvolution.cu
- lib/THCUNN/VolumetricMaxPooling.cu
- lib/THCUNN/im2col.h
- lib/THCUNN/vol2col.h
Thanks to @ngimel for the suggestion in https://github.com/torch/cunn/issues/284#issuecomment-223352745
> making error checking consistent, always and simple

- lib/THCUNN/VolumetricAveragePooling.cu
- lib/THCUNN/VolumetricMaxPooling.cu
Tested all codepaths in Max and Average pooling via base script https://gist.github.com/7c2b930477b1b074708a3df73bd7b929
Fixes https://github.com/torch/cunn/issues/197 and https://github.com/torch/cunn/issues/284
cc: @cvondrick
> fixing Volumetric Average and Max Pooling for large inputs

- lib/THCUNN/THCUNN.h
- lib/THCUNN/VolumetricMaxUnpooling.cu
- test.lua
This is the CUDA version of the [this](https://github.com/torch/nn/pull/569) introduced in `nn`.
Added Tests.
modified:   THCUNN.h
new file:   VolumetricMaxUnpooling.cu
modified:   test.lua
> Added CUDA version of VolumetricMaxUnpooling

- lib/THCUNN/THCUNN.h
- lib/THCUNN/VolumetricReplicationPadding.cu
- test.lua
CUDA version of:
https://github.com/torch/nn/pull/853
> Added VolumetricReplicationPadding.

- lib/THCUNN/SpatialFullConvolution.cu
- test.lua
Adds NoBias for nn.SpatialFullConvolution
> Add noBias for nn.SpatialFullConvolution

- lib/THCUNN/LookupTable.cu
Fixes https://github.com/torch/distro/issues/127
> fix for std::pow ambiguousness

- lib/THCUNN/BatchNormalization.cu
- test.lua
There were two problems with the implementation for pre-Kepler cards:
1. `MAX_BLOCK_SIZE` wasn't accurate which caused crashes if the image size (dim 3 x dim 4) was larger than 256.
2. The `__syncthreads()` in warpSum() caused an incorrect computation (the tests failed) because not every warp in the block executes the `warpSum()` at the end of the [`reduce()`](https://github.com/torch/cunn/blob/86d9f566baa8c0950e41a41f49965ad88611b514/lib/THCUNN/BatchNormalization.cu#L109) function 
Fixes #298
> Fix BatchNormalization warpSum for pre-Kepler cards

- lib/THCUNN/THCUNN.h
- lib/THCUNN/VolumetricDilatedConvolution.cu
- lib/THCUNN/VolumetricFullConvolution.cu
- lib/THCUNN/vol2col.h
- test.lua
CUDA version of https://github.com/torch/nn/pull/902
> Volumetric Dilated Convolution

- lib/THCUNN/BatchNormalization.cu
Example:
```
bn = nn.BatchNormalization(100):cuda()
bn:evaluate()
bn:forward(torch.CudaTensor(147000, 100):zero())
cutorch.synchronize()
```
Fixes https://github.com/torch/nn/issues/907
Per-activation batch norm still needs to be optimized. It currently runs with one thread per block. Improving per-activation performance is left for a future PR.
> Fix "invalid configuration" when using very large batch sizes in evaluate mode

- lib/THCUNN/ClassNLLCriterion.cu
- lib/THCUNN/SpatialClassNLLCriterion.cu
- lib/THCUNN/THCUNN.h
Depends on https://github.com/torch/nn/pull/979
> making ClassNLLCriterion targets consistent between cpu and cuda

- lib/THCUNN/SpatialUpSamplingBilinear.cu
- lib/THCUNN/THCUNN.h
- test.lua
Needed for PR https://github.com/torch/nn/pull/1006
> fixes to upsampling bilinear API

- DataParallelTable.lua
I found another problematic context: when input & output dimension differs (for instance input is table, and output is tensor) - the hack of sending back inputGpu[i] does not work and we hit problems in _concat.
I propose the attached patch - which is simpler and avoid sending back inputGpu[i] as output for empty batch assignments.
_distribute returns the maximum gpuIdx index necessary and _exec have an optional parameter to launch process up to the gpuIdx index.
note that this type of issue shows while introducing data parallelism on NMT engine - the batches have identical length sentences, so it happens quite often that we have batches with very few items.
> more robust support of small batches when input/output dimensions differ

- lib/THCUNN/THCHalfAutoNumerics.cuh
They have been moved to THCNumerics already.
> Remove mul/div from THCHalfAutoNumerics

- THCUNN.lua
- test.lua
This fixes loading problem when GPU doesn't support half type.
> Reference HalfTensor when it exist

- lib/THCUNN/generic/SpatialConvolutionLocal.cu
- test.lua
> SpatialConvolutionLocal uses baddbmm

- lib/THCUNN/generic/SpatialAveragePooling.cu
- lib/THCUNN/generic/SpatialDilatedMaxPooling.cu
Cuda version of https://github.com/torch/nn/pull/1049
> Fix shapeCheck in Spatial Pooling modules

- lib/THCUNN/SpatialFractionalMaxPooling.cu
> fix half type numerics issue in SpatialFractionalMaxPooling

- DataParallelTable.lua
- test_DataParallelTable.lua
Also adds currently disabled support for Half tensors,
which requires torch.HalfTensor to enable.
> Add support for Double tensors to DataParallelTable.

- THCUNN.lua
- test.lua
Hi,
Send this PR instead of keeping it as patch in distro.
Thanks,
> explicitly load THC for windows

- THCUNN.lua
- lib/THCUNN/SparseLinear.cu
- lib/THCUNN/generic/BatchNormalization.cu
- lib/THCUNN/generic/ELU.cu
- lib/THCUNN/generic/HardTanh.cu
- lib/THCUNN/generic/LeakyReLU.cu
- lib/THCUNN/generic/LookupTable.cu
- lib/THCUNN/generic/MarginCriterion.cu
- lib/THCUNN/generic/MultiMarginCriterion.cu
- lib/THCUNN/generic/PReLU.cu
- lib/THCUNN/generic/SoftPlus.cu
- lib/THCUNN/generic/SoftShrink.cu
- lib/THCUNN/generic/SparseLinear.cu
- lib/THCUNN/generic/SpatialConvolutionLocal.cu
- lib/THCUNN/generic/SpatialConvolutionMM.cu
- lib/THCUNN/generic/SpatialCrossMapLRN.cu
- lib/THCUNN/generic/SpatialDilatedConvolution.cu
- lib/THCUNN/generic/SpatialFullConvolution.cu
- lib/THCUNN/generic/SpatialSubSampling.cu
- lib/THCUNN/generic/Sqrt.cu
- lib/THCUNN/generic/THCUNN.h
- lib/THCUNN/generic/TemporalConvolution.cu
- lib/THCUNN/generic/Threshold.cu
- lib/THCUNN/generic/VolumetricConvolution.cu
- lib/THCUNN/generic/VolumetricDilatedConvolution.cu
- lib/THCUNN/generic/VolumetricFullConvolution.cu
- test.lua
> Revert "Convert real to accreal in libTHCUNN"

- lib/THCUNN/GatedLinearUnit.cu
- lib/THCUNN/generic/GatedLinearUnit.cu
- lib/THCUNN/generic/THCUNN.h
- test.lua
recommitting these changes. fixed the genericization issues caught in #425.
> cuda implementation of Gated Linear Unit, fixed issues with genericization

- lib/THCUNN/generic/THCUNN.h
> Use THCTensor rather than THCudaTensor in GatedLinearUnit

- lib/THCUNN/LogSoftMax.cu
- lib/THCUNN/generic/SpatialClassNLLCriterion.cu
* Shape checks for SpatialClassNLLCriterion
* Use a more numerically stable formula for spatial LogSoftMax
> Improvements for spatial functions

- THCUNN.lua
- lib/THCUNN/SparseLinear.cu
- lib/THCUNN/generic/BatchNormalization.cu
- lib/THCUNN/generic/ELU.cu
- lib/THCUNN/generic/HardTanh.cu
- lib/THCUNN/generic/LeakyReLU.cu
- lib/THCUNN/generic/LookupTable.cu
- lib/THCUNN/generic/MarginCriterion.cu
- lib/THCUNN/generic/MultiMarginCriterion.cu
- lib/THCUNN/generic/PReLU.cu
- lib/THCUNN/generic/SoftPlus.cu
- lib/THCUNN/generic/SoftShrink.cu
- lib/THCUNN/generic/SparseLinear.cu
- lib/THCUNN/generic/SpatialConvolutionLocal.cu
- lib/THCUNN/generic/SpatialConvolutionMM.cu
- lib/THCUNN/generic/SpatialCrossMapLRN.cu
- lib/THCUNN/generic/SpatialDilatedConvolution.cu
- lib/THCUNN/generic/SpatialFullConvolution.cu
- lib/THCUNN/generic/SpatialSubSampling.cu
- lib/THCUNN/generic/Sqrt.cu
- lib/THCUNN/generic/THCUNN.h
- lib/THCUNN/generic/TemporalConvolution.cu
- lib/THCUNN/generic/TemporalRowConvolution.cu
- lib/THCUNN/generic/Threshold.cu
- lib/THCUNN/generic/VolumetricConvolution.cu
- lib/THCUNN/generic/VolumetricDilatedConvolution.cu
- lib/THCUNN/generic/VolumetricFullConvolution.cu
- test.lua
- This reverts commit 0d85922d116879448485ef88ae21e83a9255a0b0.
- Includes fixes for TemporalRowConvolution
> Convert real to accreal in libTHCUNN

- lib/THCUNN/VolumetricFractionalMaxPooling.cu
- lib/THCUNN/generic/THCUNN.h
- lib/THCUNN/generic/VolumetricFractionalMaxPooling.cu
https://github.com/torch/nn/pull/1123
> VolumetricFractionalMaxPooling like spatial

- lib/THCUNN/SpatialAdaptiveAveragePooling.cu
- lib/THCUNN/generic/SpatialAdaptiveAveragePooling.cu
- lib/THCUNN/generic/THCUNN.h
- test.lua
The code is based on SpatialAdaptiveMaxPooling. This use the same pool region algorithm as SpatialAdaptiveMaxPooling.
> Add SpatialAdaptiveAveragePooling.

- DataParallelTable.lua
There exist use-cases in which the serialization code for a model is not thread-safe, for instance, when the serialization code has non-thread-safe dependencies.
This PR adds an option to perform synchronous copies of the model onto all the GPUs in order to prevent race conditions. This change should not break existing code.
> [DPT] Add option for synchronous copy of model to GPUs

- lib/THCUNN/generic/LogSoftMax.cu
- lib/THCUNN/generic/SparseLinear.cu
- lib/THCUNN/generic/SpatialConvolutionLocal.cu
- lib/THCUNN/generic/TemporalConvolution.cu
- lib/THCUNN/generic/TemporalRowConvolution.cu
- Related to https://github.com/torch/nn/issues/1185
> Using temporary variables when performing transpose + addmm

- lib/THCUNN/IndexLinear.cu
- lib/THCUNN/SparseLinear.cu
- lib/THCUNN/generic/IndexLinear.cu
- lib/THCUNN/generic/THCUNN.h
- test.lua
The cunn implementation of IndexLinear described here: https://github.com/torch/nn/pull/1181
> Adding Indexlinear

- lib/THCUNN/ClassNLLCriterion.cu
If the target is zero, loss and gradient of input are reminded to be zero. It
is useful for variable-length NL generation models.
> Update to ignore zero targets

- lib/THCUNN/ClassNLLCriterion.cu
Reverts torch/cunn#458
Right now nn and cunn are broken wrt each other.
I'll remerge this PR once @nicholas-leonard sends his cunn changes.
> Revert "Update to ignore zero targets"

- lib/THCUNN/generic/SpatialDepthWiseConvolution.cu
Calling :noBias() on nn.SpatialDepthWiseConvolution results in segfaults during both forward and backward passes. PR fixes the issue.
> Fix segfault in SpatialDepthWiseConvolution w/o bias

- test.lua
Cunn tests for the recently added UpSampling module, have tested and they build / succeed.
Mike
> Added cunn tests for UpSampling module.

- test.lua
Updated unit tests for https://github.com/torch/nn/pull/1271
> BN supports batchsize=1
